spring:
#  security:
#    user:
#      name: user
#      password: devdojo
  config:
    import: optional:classpath:.env[.properties]
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user_service?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExists=true
    username: ${ENV_ROOT_USER:root}
    password: ${ENV_ROOT_PASSWORD:devdojo}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  web:
    error:
      include-stacktrace: on_param
  threads:
    virtual:
      enabled: true
logging:
  level:
    org.springframework.security: debug
#    net.ttddyy.dsproxy.listener: debug
server:
  port: 8090