spring:
  application:
    name: anime-service
  web:
    error:
      include-stacktrace: on_param
  threads:
    virtual:
      enabled: true

server:
  servlet:
    context-path: /
  tomcat:
    threads:
      max: 20

logging:
  level:
    root: INFO
    academy.devdojo: DEBUG

database:
  url: localhost:3306
  username: devdojo
  password: devdojo
